default_chain: stride-testnet
chains:
  gaia-testnet:
    key: gaia
    chain-id: GAIA
    rpc-addr: http://46.101.158.173:25657
    grpc-addr: http://46.101.158.173:25090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: stride
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://46.101.158.173:26657
    grpc-addr: http://46.101.158.173:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
